language: generic
os:
  - linux
  - osx
sudo: false
before_install:
  - git submodule update --init --recursive
  # This is needed for vim-spec.
  # For a ruby project this is done automatically but since we are using
  # python as a language for travis we do this by hand.
  - bundle install --jobs=3 --retry=3
install:
  # source because it sets up env vars on some platforms
  - source travis/travis_install.sh
script: ./run_tests.py
env:
  matrix:
    - YCMD_PYTHON_VERSION=2.7
    - YCMD_PYTHON_VERSION=2.6
addons:
  apt:
    sources:
     - deadsnakes
    packages:
     - vim-gtk
     - python2.6
     - python2.6-dev
     - python2.7
     - python2.7-dev
     - python-virtualenv
cache:
  directories:
    - $HOME/.cache/pip
