language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - git submodule update --init --recursive
  # Install vroom.
  - wget https://github.com/google/vroom/releases/download/v0.12.0/vroom_0.12.0-1_all.deb
  - sudo dpkg -i vroom_0.12.0-1_all.deb
  # Install vim-gnome (vroom require +clientserver)
  - sudo apt-get install vim-gtk
  # Vroom's vim mode currently requires a running X server.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r python/test_requirements.txt
script: ./run_tests.sh
