language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install vim-gtk
install:
  - pip install -r python/test_requirements.txt
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
    # For a ruby project this is done automatically but since we are using
    # python as a language for travis we do this by hand
  - bundle install --jobs=3 --retry=3
script: ./run_tests.sh
